.\#
.\# Yet Another Pulsar Processor Commands
.\# yapp_viewdata Manual Page
.\#
.\# Created by Jayanth Chennamangalam on 2011.03.20
.\#

.TH YAPP_VIEWDATA 1 "2011-03-20" "YAPP 1.0.0" \
"Yet Another Pulsar Processor"


.SH NAME
yapp_viewdata \- view raw dynamic spectrum data


.SH SYNOPSIS
.B view_data
[options]
.I dynamic-spectrum-data-file


.SH DESCRIPTION
Plots raw dynamic spectrum data to PGPLOT device.


.SH OPTIONS
.TP
\-h
display a short help text
.TP
\-s
percentage of data to be skipped
.TP
\-S
length of data in seconds, to be skipped
.TP
\-p
percentage of data to be processed (default is 100)
.TP
\-P
length of data in seconds, to be processed (default is all)
.TP
\-b
number of samples read in one block (default is 4096 samples)
.TP
\-c
number of sigmas above threshold; will clip anything above this level
.TP
\-m
MATLAB colour map for plotting (default is 'jet')
.TP
\-i
invert background and foreground colours in plots
.TP
\-n
run in non-interactive mode
.TP
\-v
display the version


.SH EXAMPLE
.TP
yapp_viewdata -b 8192 -m hsv data.fil


.SH SEE ALSO
.BR yapp_viewmetadata (1)


.SH AUTHOR
.TP 
Written by Jayanth Chennamangalam <jchennam@mix.wvu.edu> with guidance from \
Avinash Deshpande. Yogesh Maan, Isaac Backus, and Duncan Lorimer contributed \
to this work.

