.\#
.\# Yet Another Pulsar Processor Commands
.\# yapp_viewmetadata Manual Page
.\#
.\# Created by Jayanth Chennamangalam on 2010.09.23
.\#

.TH YAPP_VIEWMETADATA 1 "2011-04-01" "YAPP 1.0.0" \
"Yet Another Pulsar Processor"


.SH NAME
yapp_viewmetadata \- view metadata/data header/configuration information


.SH SYNOPSIS
.B yapp_viewmetadata
[options]
.I dynamic-spectrum-data-file


.SH DESCRIPTION
Prints metadata/data header/configuration information to standard output.


.SH OPTIONS
.TP
\-h
display a short help text
.TP
\-v
display the version


.SH EXAMPLE
.TP
yapp_viewmetadata data.fil


.SH SEE ALSO
.BR yapp_viewdata (1)


.SH AUTHOR
.TP 
Written by Jayanth Chennamangalam <jchennam@mix.wvu.edu> with guidance from \
Avinash Deshpande. Yogesh Maan, Isaac Backus, and Duncan Lorimer contributed \
to this work.

