.\#
.\# Yet Another Pulsar Processor Commands
.\# yapp_ym2fil Manual Page
.\#
.\# Created by Jayanth Chennamangalam on 2015.09.11
.\#

.TH YAPP_YM2FIL 1 "2015-09-11" "YAPP 3.6-beta" \
"Yet Another Pulsar Processor"


.SH NAME
yapp_ym2fil \- convert yapp_viewmetadata output to SIGPROC '.fil'


.SH SYNOPSIS
.B yapp_ym2fil
[options]
.I data-file


.SH DESCRIPTION
Converts the output of yapp_viewmetadata to SIGPROC '.fil'.


.SH OPTIONS
.TP
.B \-h, --help
Display a short help text.
.TP
.B \-v, --version
Display the version.


.SH EXAMPLE
.TP
Converts the output of the first command - stored in data.ym - to \
data.header.fil.
.P
yapp_viewmetadata data.fil > data.ym
.br
yapp_ym2fil data.ym


.SH SEE ALSO
.BR yapp_dat2tim (1),
.BR yapp_viewmetadata (1),
.BR yapp_viewdata (1),
.BR yapp_dedisperse (1),
.BR yapp_smooth (1),
.BR yapp_filter (1),
.BR yapp_add (1),
.BR yapp_fold (1),
.BR yapp_subtract (1),
.BR yapp_split(1),
.BR yapp_siftpulses (1)


.SH AUTHOR
.TP 
Written by Jayanth Chennamangalam. http://jayanthc.github.com/yapp/

