.\#
.\# Yet Another Pulsar Processor Commands
.\# yapp_viewmetadata Manual Page
.\#
.\# Created by Jayanth Chennamangalam on 2010.09.23
.\#

.TH YAPP_VIEWMETADATA 1 "2013-06-02" "YAPP 3.4-beta" \
"Yet Another Pulsar Processor"


.SH NAME
yapp_viewmetadata \- view metadata/data header/configuration information


.SH SYNOPSIS
.B yapp_viewmetadata
[options]
.I data-file


.SH DESCRIPTION
As the name indicates, this program is used to display metadata/data \
header/configuration information associated with a data file. The following \
file types are supported:
.P
1. Search-mode PSRFITS
.br
2. DAS .spec filterbank format
.br
3. SIGPROC .fil filterbank format (including the headerless version, provided \
a .fhd configuration file is present in the same directory)
.br
4. SIGPROC .tim time series format


.SH OPTIONS
.TP
.B \-h, --help
Display a short help text.
.TP
.B \-v, --version
Display the version.

.TP
The data file name may be a composed of standard shell wildcards such as * or \
?.


.SH EXAMPLES
.TP
The following displays the metadata for the SIGPROC filterbank file data.fil. \
If this is a headerless filterbank file, it is expected that a file with \
metadata information, named data.fhd is present in the same directory as the \
data file.
.TP
yapp_viewmetadata data.fil
.TP
The following displays the metadata for all DAS filterbank files in the \
current working directory.
.TP
yapp_viewmetadata *.spec


.SH SEE ALSO
.BR yapp_fits2fil (1),
.BR yapp_dat2tim (1),
.BR yapp_viewdata (1),
.BR yapp_ft (1),
.BR yapp_dedisperse (1),
.BR yapp_smooth (1),
.BR yapp_filter (1),
.BR yapp_add (1),
.BR yapp_fold (1),
.BR yapp_subtract (1),
.BR yapp_stacktim (1),
.BR yapp_siftpulses (1)


.SH AUTHOR
.TP 
Written by Jayanth Chennamangalam. http://jayanthc.github.com/yapp/

