/**
 * @file yapp_showinfo.c
 * Shows information on the current YAPP installation, such as file types
 * supported, colour map names, etc.
 *
 * @verbatim
 * Usage: yapp_showinfo [options]
 *     -h  --help                           Display this usage information
 *     -v  --version                        Display the version @endverbatim
 *
 * @author Jayanth Chennamangalam
 * @date 2017.03.24
 */

#include "yapp.h"
#include "colourmap.h"

/**
 * The build version string, maintained in the file version.c, which is
 * generated by makever.c.
 */
extern const char *g_pcVersion;

int main(int argc, char *argv[])
{
    int iRet = YAPP_RET_SUCCESS;
    int i = 0;
    char acString[LEN_GENSTRING]  = {0};
    const char *pcProgName = NULL;
    int iNextOpt = 0;
    /* valid short options */
    const char* const pcOptsShort = "hv";
    /* valid long options */
    const struct option stOptsLong[] = {
        { "help",                   0, NULL, 'h' },
        { "version",                0, NULL, 'v' },
        { NULL,                     0, NULL, 0   }
    };

    /* get the filename of the program from the argument list */
    pcProgName = argv[0];

    /* parse the input */
    do
    {
        iNextOpt = getopt_long(argc, argv, pcOptsShort, stOptsLong, NULL);
        switch (iNextOpt)
        {
            case 'h':   /* -h or --help */
                /* print usage info and terminate */
                PrintUsage(pcProgName);
                return YAPP_RET_SUCCESS;

            case 'v':   /* -v or --version */
                /* display the version */
                (void) printf("%s\n", g_pcVersion);
                return YAPP_RET_SUCCESS;

            case '?':   /* user specified an invalid option */
                /* print usage info and terminate with error */
                (void) fprintf(stderr, "ERROR: Invalid option!\n");
                PrintUsage(pcProgName);
                return YAPP_RET_ERROR;

            case -1:    /* done with options */
                break;

            default:    /* unexpected */
                assert(0);
        }
    } while (iNextOpt != -1);

    /* show about */
    (void) printf("-----------------------------------------------------------"
                  "--------------------\n");
    (void) printf("    YAPP\n");
    (void) printf("    Yet Another Pulsar Processor BETA\n");
    (void) printf("    Version: %s\n", g_pcVersion);
    (void) printf("\n");
    (void) printf("    Created by Jayanth Chennamangalam\n");
    (void) printf("    https://jayanthchennamangalam.com\n");
    (void) printf("\n");

    /* show supported file types */
    (void) printf("    YAPP supports the following file types:\n");
    for (i = 0; i < YAPP_FORMAT_NUMSUPPORTED; ++i)
    {
        iRet = YAPP_GetDescFromFormat(i, acString);
        if (iRet != YAPP_RET_SUCCESS)
        {
            (void) fprintf(stderr,
                           "ERROR: Getting description failed for format %d!\n",
                           i);
            return YAPP_RET_ERROR;
        }
        (void) printf("        %s\n", acString);
    }
    (void) printf("\n");

    /* show supported colourmap names */
    (void) printf("    YAPP plotting tools support the following "
                  "colourmaps:\n");
    for (i = 0; i < NUM_CMAPS; ++i)
    {
        iRet = GetNameFromColourMap(i, acString);
        if (iRet != YAPP_RET_SUCCESS)
        {
            (void) fprintf(stderr,
                           "ERROR: Getting name failed for colourmap %d!\n",
                           i);
            return YAPP_RET_ERROR;
        }
        (void) printf("        %s\n", acString);
    }

    (void) printf("-----------------------------------------------------------"
                  "--------------------\n");

    return YAPP_RET_SUCCESS;
}

/*
 * Prints usage information
 */
void PrintUsage(const char *pcProgName)
{
    (void) printf("Usage: %s [options]\n",
                  pcProgName);
    (void) printf("    -h  --help                          ");
    (void) printf("Display this usage information\n");
    (void) printf("    -v  --version                       ");
    (void) printf("Display the version\n");

    return;
}

