/**
 * @file yapp_replacemetadata.c
 * Reads metadata from a .fhd file, and replaces the existing metadata in a
 * .fil or .tim file with it.
 *
 * @verbatim
 * Usage: yapp_replacemetadata [options] <data-file>
 *     -h  --help                           Display this usage information
 *     -v  --version                        Display the version @endverbatim
 *     -m  --metadata-file <file>           File with metadata
 *
 * @author Jayanth Chennamangalam
 * @date 2015.07.05
 */

#include "yapp.h"
#include "yapp_sigproc.h"   /* for SIGPROC filterbank file format support */

/**
 * The build version string, maintained in the file version.c, which is
 * generated by makever.c.
 */
extern const char *g_pcVersion;

int main(int argc, char *argv[])
{
    char *pcFileData = NULL;
    int iFormat = DEF_FORMAT;
    int iRet = YAPP_RET_SUCCESS;
    YUM_t stYUM = {{0}};
    char acFileMetadata[LEN_GENSTRING] = {0};
    const char *pcProgName = NULL;
    int iNextOpt = 0;
    /* valid short options */
    const char* const pcOptsShort = "hvm:";
    /* valid long options */
    const struct option stOptsLong[] = {
        { "help",                   0, NULL, 'h' },
        { "version",                0, NULL, 'v' },
        { "metadata-file",          0, NULL, 'm' },
        { NULL,                     0, NULL, 0   }
    };

    /* get the filename of the program from the argument list */
    pcProgName = argv[0];

    /* parse the input */
    do
    {
        iNextOpt = getopt_long(argc, argv, pcOptsShort, stOptsLong, NULL);
        switch (iNextOpt)
        {
            case 'h':   /* -h or --help */
                /* print usage info and terminate */
                PrintUsage(pcProgName);
                return YAPP_RET_SUCCESS;

            case 'v':   /* -v or --version */
                /* display the version */
                (void) printf("%s\n", g_pcVersion);
                return YAPP_RET_SUCCESS;

            case 'm':   /* -m or --metadata-file */
                /* file with metadata */
                (void) strncpy(acFileMetadata, optarg, LEN_GENSTRING);
                return YAPP_RET_SUCCESS;

            case '?':   /* user specified an invalid option */
                /* print usage info and terminate with error */
                (void) fprintf(stderr, "ERROR: Invalid option!\n");
                PrintUsage(pcProgName);
                return YAPP_RET_ERROR;

            case -1:    /* done with options */
                break;

            default:    /* unexpected */
                assert(0);
        }
    } while (iNextOpt != -1);

    /* no arguments */
    if (argc <= optind)
    {
        (void) fprintf(stderr, "ERROR: Input file not specified!\n");
        PrintUsage(pcProgName);
        return YAPP_RET_ERROR;
    }

    /* get the input filename */
    pcFileData = argv[optind];

    /* determine the file type */
    iFormat = YAPP_GetFileType(pcFileData);
    if (YAPP_RET_ERROR == iFormat)
    {
        (void) fprintf(stderr,
                       "ERROR: File type determination failed!\n");
        return YAPP_RET_ERROR;
    }
    if (!((YAPP_FORMAT_FIL == iFormat)
          || (YAPP_FORMAT_DTS_TIM == iFormat)))
    {
        (void) fprintf(stderr,
                       "ERROR: Invalid file type!\n");
        return YAPP_RET_ERROR;
    }

    iRet = YAPP_ReadMetadata(pcFileData, iFormat, &stYUM);
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr, "ERROR: Reading metadata failed!\n");
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    iRet = YAPP_WriteMetadata(pcFileData, iFormat, stYUM);
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr, "ERROR: Writing metadata failed!\n");
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    /* clean up */
    YAPP_CleanUp();

    return YAPP_RET_SUCCESS;
}

/*
 * Prints usage information
 */
void PrintUsage(const char *pcProgName)
{
    (void) printf("Usage: %s [options] <data-file>\n",
                  pcProgName);
    (void) printf("    -h  --help                          ");
    (void) printf("Display this usage information\n");
    (void) printf("    -v  --version                       ");
    (void) printf("Display the version\n");
    (void) printf("    -m  --metadata-file <file>          ");
    (void) printf("File with metadata\n");

    return;
}

