/*
 * @file yapp_viewdata.c
 * Program to plot raw dynamic spectrum data.
 *
 * @verbatim
 * Usage: yapp_viewdata [options] <data-file>
 *     -h  --help                           Display this usage information
 *     -s  --skip <time>                    The length of data in seconds, to
 *                                          be skipped
 *                                          (default is 0 s)
 *     -p  --proc <time>                    The length of data in seconds, to
 *                                          be processed
 *                                          (default is all)
 *     -n  --nsamp <samples>                Number of samples read in one block
 *                                          (default is 4096 samples)
 *     -b  --nband <bands>                  Number of bands for spliced
 *                                          filterbank files
 *     -c  --clip-level <level>             Number of sigmas above threshold;
 *                                          will clip anything above this level
 *     -a  --no-abs-scale                   Use relative scale for plotting per
 *                                          block
 *     -d  --show-bandpass                  Show the bandpass for each block
 *     -t  --period <period>                Period of the pulsar in ms
 *     -r  --phase <phase>                  Phase of the first pulse with
 *                                          respect to the first sample
 *     -m  --colour-map <name>              Colour map for plotting
 *                                          (default is 'jet')
 *     -i  --invert                         Invert the background and
 *                                          foreground colours in plots
 *     -e  --non-interactive                Run in non-interactive mode
 *     -v  --version                        Display the version @endverbatim
 *
 * @author Jayanth Chennamangalam
 * @date 2008.11.14
 */

/* TODO: 1. ORT: beam flip time section anomaly for last block
& MST radar data reads nan or inf for the last few samples of
            data*/

#include "yapp.h"
#include "yapp_sigproc.h"   /* for SIGPROC filterbank file format support */
#include "colourmap.h"
#include "yapp_hdf5.h"
#include <hdf5.h>

/**
 * The build version string, maintained in the file version.c, which is
 * generated by makever.c.
 */
extern const char *g_pcVersion;

/* PGPLOT device ID */
extern int g_iPGDev;

/* data file */
extern FILE *g_pFData;

/* the following are global only to enable cleaning up in case of abnormal
   termination, such as those triggered by SIGINT or SIGTERM */
char *g_pcIsTimeGood = NULL;
float *g_pfBuf = NULL;
float *g_pfPlotBuf = NULL;
float *g_pfXAxis = NULL;
float *g_pfXAxisOld = NULL;
float *g_pfYAxis = NULL;
float *g_pfBandpass = NULL;

int main(int argc, char *argv[])
{
    char *pcFileData = NULL;
    int iFormat = DEF_FORMAT;
    double dDataSkipTime = 0.0;
    double dDataProcTime = 0.0;
    YUM_t stYUM = {{0}};
    double dTNextBF = 0.0;
    float *pfTimeSectGain = NULL;
    int iBlockSize = DEF_SIZE_BLOCK;
    int iTotSampsPerBlock = 0;  /* iNumChans * iBlockSize */
    float fStatBW = 0.0;
    float fNoiseRMS = 0.0;
    float fClipLevel = 0.0;
    char cUseAbsScale = YAPP_TRUE;
    char cShowBandpass = YAPP_FALSE;
    double dNumSigmas = 0.0;
    double dTSampInSec = 0.0;   /* holds sampling time in s */
    int iNumBands = 0;
    double dTNow = 0.0;
    int iTimeSect = 0;
    int iBadTimeSect = 0;
    char cIsInBadTimeRange = YAPP_FALSE;
    float *pfSpectrum = NULL;
    long lBytesToSkip = 0;
    long lBytesToProc = 0;
    int iTimeSampsToSkip = 0;
    int iTimeSampsToProc = 0;
    int iNumReads = 0;
    int iTotNumReads = 0;
    int iReadBlockCount = 0;
    hid_t hFile = 0;
    hid_t hDataset = 0;
    hid_t hDataspace = 0;
    hid_t hMemDataspace = 0;
    hid_t hType = 0;
    hsize_t hMemDims[YAPP_HDF5_DYNSPEC_RANK] = {0};
    hsize_t hOffset[YAPP_HDF5_DYNSPEC_RANK] = {0};
    hsize_t hCount[YAPP_HDF5_DYNSPEC_RANK] = {0};
    char cIsLastBlock = YAPP_FALSE;
    int iRet = YAPP_RET_SUCCESS;
    float fDataMin = 0.0;
    float fDataMax = 0.0;
    char cIsFirst = YAPP_TRUE;
    int iReadItems = 0;
    float fButX = 0.0;
    float fButY = 0.0;
    char cCurChar = 0;
    int iNumSamps = 0;
    double dPeriod = 0.0;
    double dStartPhase = 0.0;
    double dPhase = 0.0;
    double dMinPhaseDiff = 0.0;
    long int lSampCount = 0;
    int iDiff = 0;
    int i = 0;
    int j = 0;
    int k = 0;
    int l = 0;
    int m = 0;
    char acLabel[LEN_GENSTRING] = {0};
    int iColourMap = DEF_CMAP;
    int iInvCols = YAPP_FALSE;
    char cIsNonInteractive = YAPP_FALSE;
    const char *pcProgName = NULL;
    int iNextOpt = 0;
    /* valid short options */
    const char* const pcOptsShort = "hs:p:n:b:c:adt:r:m:iev";
    /* valid long options */
    const struct option stOptsLong[] = {
        { "help",                   0, NULL, 'h' },
        { "skip",                   1, NULL, 's' },
        { "proc",                   1, NULL, 'p' },
        { "nsamp",                  1, NULL, 'n' },
        { "nband",                  1, NULL, 'b' },
        { "clip-level",             1, NULL, 'c' },
        { "no-abs-range",           0, NULL, 'a' },
        { "show-bandpass",          0, NULL, 'd' },
        { "period",                 1, NULL, 't' },
        { "phase",                  1, NULL, 'r' },
        { "colour-map",             1, NULL, 'm' },
        { "invert",                 0, NULL, 'i' },
        { "non-interactive",        0, NULL, 'e' },
        { "version",                0, NULL, 'v' },
        { NULL,                     0, NULL, 0   }
    };

    /* get the filename of the program from the argument list */
    pcProgName = argv[0];

    /* parse the input */
    do
    {
        iNextOpt = getopt_long(argc, argv, pcOptsShort, stOptsLong, NULL);
        switch (iNextOpt)
        {
            case 'h':   /* -h or --help */
                /* print usage info and terminate */
                PrintUsage(pcProgName);
                return YAPP_RET_SUCCESS;

            case 's':   /* -s or --skip */
                /* set option */
                dDataSkipTime = atof(optarg);
                break;

            case 'p':   /* -p or --proc */
                /* set option */
                dDataProcTime = atof(optarg);
                break;

            case 'n':   /* -n or --nsamp */
                /* set option */
                iBlockSize = atoi(optarg);
                /* validate - PGPLOT does not like iBlockSize = 1 */
                if (iBlockSize < 2)
                {
                    (void) fprintf(stderr,
                                   "ERROR: Number of samples must be > 1!\n");
                    PrintUsage(pcProgName);
                    return YAPP_RET_ERROR;
                }
                break;

            case 'b':   /* -b or --nband */
                /* set option */
                iNumBands = atoi(optarg);
                break;

            case 'c':   /* -c or --clip-level */
                /* set option */
                fClipLevel = (float) atof(optarg);
                break;

            case 'a':   /* -a or --no-abs-range */
                /* set option */
                cUseAbsScale = YAPP_FALSE;
                break;

            case 'd':   /* -d or --show-bandpass */
                /* set option */
                cShowBandpass = YAPP_TRUE;
                break;

            case 't':   /* -t or --period */
                /* set option */
                dPeriod = atof(optarg);
                break;

            case 'r':   /* -r or --phase */
                /* set option */
                dStartPhase = atof(optarg);
                break;

            case 'm':   /* -m or --colour-map */
                /* set option */
                iColourMap = GetColourMapFromName(optarg);
                break;

            case 'i':  /* -i or --invert */
                /* set option */
                iInvCols = YAPP_TRUE;
                break;

            case 'e':  /* -e or --non-interactive */
                /* set option */
                cIsNonInteractive = YAPP_TRUE;
                break;

            case 'v':   /* -v or --version */
                /* display the version */
                (void) printf("%s\n", g_pcVersion);
                return YAPP_RET_SUCCESS;

            case '?':   /* user specified an invalid option */
                /* print usage info and terminate with error */
                (void) fprintf(stderr, "ERROR: Invalid option!\n");
                PrintUsage(pcProgName);
                return YAPP_RET_ERROR;

            case -1:    /* done with options */
                break;

            default:    /* unexpected */
                assert(0);
        }
    } while (iNextOpt != -1);

    /* no arguments */
    if (argc <= optind)
    {
        (void) fprintf(stderr, "ERROR: Input file not specified!\n");
        PrintUsage(pcProgName);
        return YAPP_RET_ERROR;
    }

    /* register the signal-handling function */
    iRet = YAPP_RegisterSignalHandlers();
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr,
                       "ERROR: Handler registration failed!\n");
        return YAPP_RET_ERROR;
    }

    /* if absolute scaling is not used, can't clip */
    if (!cUseAbsScale && fClipLevel != 0.0)
    {
        (void) fprintf(stderr,
                       "WARNING: "
                       "Cannot perform thresholding with relative scaling!\n");
        fClipLevel = 0.0;
    }

    /* get the input filename */
    pcFileData = argv[optind];

    /* determine the file type */
    iFormat = YAPP_GetFileType(pcFileData);
    if (YAPP_RET_ERROR == iFormat)
    {
        (void) fprintf(stderr,
                       "ERROR: File type determination failed!\n");
        return YAPP_RET_ERROR;
    }
    if (!((YAPP_FORMAT_FIL == iFormat)
          || (YAPP_FORMAT_SPEC == iFormat)
          || (YAPP_FORMAT_DTS_TIM == iFormat)
          || (YAPP_FORMAT_DTS_DAT == iFormat)
          || (YAPP_FORMAT_HDF5 == iFormat)))
    {
        (void) fprintf(stderr,
                       "ERROR: Invalid file type!\n");
        return YAPP_RET_ERROR;
    }

    /* read metadata */
    iRet = YAPP_ReadMetadata(pcFileData, iFormat, &stYUM);
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr,
                       "ERROR: Reading metadata failed for file %s!\n",
                       pcFileData);
        return YAPP_RET_ERROR;
    }
    /* kludge: the rest of the code expects stYUM.iNumChans = 1 for time series
       data, so make it 1 */
    if ((YAPP_FORMAT_DTS_TIM == iFormat)
        || (YAPP_FORMAT_DTS_DAT == iFormat)
        || (YAPP_FORMAT_DTS_DDS == iFormat))
    {
        stYUM.iNumChans = 1;
    }

    if (YAPP_FORMAT_HDF5 == iFormat)
    {
        /* current support only for 8-bit integer, 16-bit integer, and 32-bit
           single-precision floating point values */
        if (!((YAPP_SAMPSIZE_8 == stYUM.iNumBits)
              || (YAPP_SAMPSIZE_16 == stYUM.iNumBits)
              || (YAPP_SAMPSIZE_32 == stYUM.iNumBits)))
        {
            (void) fprintf(stderr,
                           "ERROR: Unsupported data type! %s only supports "
                           "8-bit ints, 16-bit ints, and 32-bit floats, "
                           "while input data is %d bits.\n",
                           pcProgName,
                           stYUM.iNumBits);
            return YAPP_RET_ERROR;
        }
    }

    /* convert sampling interval to seconds */
    dTSampInSec = stYUM.dTSamp / 1e3;

    /* copy next beam-flip time */
    dTNextBF = stYUM.dTNextBF;

    /* validate number of bands */
    if ((YAPP_TRUE == stYUM.iFlagSplicedData) && (iNumBands <= 1))
    {
        (void) fprintf(stderr,
                       "ERROR: Number of bands must be > 1 for spliced "
                       "data!\n");
        return YAPP_RET_ERROR;
    }

    /* calculate bytes to skip and read */
    if (0.0 == dDataProcTime)
    {
        dDataProcTime = (stYUM.iTimeSamps * dTSampInSec) - dDataSkipTime;
    }
    /* check if the input time duration is less than the length of the
       data */
    else if (dDataProcTime > (stYUM.iTimeSamps * dTSampInSec))
    {
        (void) fprintf(stderr,
                       "WARNING: Input time is longer than length of "
                       "data!\n");
    }

    lBytesToSkip = (long) floor(dDataSkipTime / dTSampInSec)
                                                    /* number of samples */
                          * stYUM.iNumChans
                          * stYUM.fSampSize;
    if (stYUM.fSampSize >= 2.0)
    {
        /* will be true for fSampSize = 0.5 and 1.0 */
        assert(0 == lBytesToSkip % (int) stYUM.fSampSize);
    }
    lBytesToProc = (long) floor(dDataProcTime / dTSampInSec)
                                                    /* number of samples */
                          * stYUM.iNumChans
                          * stYUM.fSampSize;
    if (stYUM.fSampSize >= 2.0)
    {
        /* will be true for fSampSize = 0.5 and 1.0 */
        assert(0 == lBytesToProc % (int) stYUM.fSampSize);
    }

    if (lBytesToSkip >= stYUM.lDataSizeTotal)
    {
        (void) fprintf(stderr,
                       "ERROR: Data to be skipped is greater than or equal to "
                       "the size of the file!\n");
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    if ((lBytesToSkip + lBytesToProc) > stYUM.lDataSizeTotal)
    {
        (void) printf("WARNING: Total data to be read (skipped and processed) "
                      "is more than the size of the file! ");
        lBytesToProc = stYUM.lDataSizeTotal - lBytesToSkip;
        dDataProcTime = ((double) lBytesToProc * dTSampInSec)
                        / (stYUM.iNumChans * stYUM.fSampSize);
        (void) printf("Newly calculated size of data to be processed: %ld "
                      "bytes\n",
                      lBytesToProc);
    }

    iTimeSampsToSkip = (int) (lBytesToSkip
                              / (stYUM.iNumChans * stYUM.fSampSize));
    (void) printf("Skipping\n"
                  "    %ld of %ld bytes\n"
                  "    %d of %d time samples\n"
                  "    %.10g of %.10g seconds\n",
                  lBytesToSkip,
                  stYUM.lDataSizeTotal,
                  iTimeSampsToSkip,
                  stYUM.iTimeSamps,
                  (iTimeSampsToSkip * dTSampInSec),
                  (stYUM.iTimeSamps * dTSampInSec));

    iTimeSampsToProc = (int) (lBytesToProc
                              / (stYUM.iNumChans * stYUM.fSampSize));
    iNumReads = (int) ceilf((float) iTimeSampsToProc / iBlockSize);
    iTotNumReads = iNumReads;

    /* change block size according to the number of samples to be processed */
    if (iTimeSampsToProc < iBlockSize)
    {
        iBlockSize = (int) ceil(dDataProcTime / dTSampInSec);
    }

    /* optimisation - store some commonly used values in variables */
    iTotSampsPerBlock = stYUM.iNumChans * iBlockSize;

    (void) printf("Processing\n"
                  "    %ld of %ld bytes\n"
                  "    %d of %d time samples\n"
                  "    %.10g of %.10g seconds\n"
                  "in %d reads with block size %d time samples...\n",
                  lBytesToProc,
                  stYUM.lDataSizeTotal,
                  iTimeSampsToProc,
                  stYUM.iTimeSamps,
                  (iTimeSampsToProc * dTSampInSec),
                  (stYUM.iTimeSamps * dTSampInSec),
                  iNumReads,
                  iBlockSize);

    (void) printf("Observation start time: %.15g MJD\n", stYUM.dTStart);

    /* calculate the threshold */
    dNumSigmas = YAPP_CalcThresholdInSigmas(iTimeSampsToProc);
    if ((double) YAPP_RET_ERROR == dNumSigmas)
    {
        (void) fprintf(stderr, "ERROR: Threshold calculation failed!\n");
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    if (!((YAPP_FORMAT_DTS_TIM == iFormat)
          || (YAPP_FORMAT_DTS_DAT == iFormat)
          || (YAPP_FORMAT_DTS_DDS == iFormat)))
    {
        fStatBW = stYUM.iNumGoodChans * stYUM.fChanBW;  /* in MHz */
        (void) printf("Usable bandwidth                  : %g MHz\n", fStatBW);
        fNoiseRMS = 1.0 / sqrt(fStatBW * stYUM.dTSamp * 1e3);
        (void) printf("Expected noise RMS                : %g\n", fNoiseRMS);
    }

    /* allocate memory for the time sample goodness flag array */
    g_pcIsTimeGood = (char *) YAPP_Malloc(iTimeSampsToProc,
                                          sizeof(char),
                                          YAPP_FALSE);
    if (NULL == g_pcIsTimeGood)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation for time sample goodness "
                       "flag array failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    /* set all elements to 'YAPP_TRUE' */
    (void) memset(g_pcIsTimeGood, YAPP_TRUE, iTimeSampsToProc);

    /* open the data file for reading */
    if (YAPP_FORMAT_HDF5 == iFormat)
    {
        hFile = H5Fopen(pcFileData, H5F_ACC_RDONLY, H5P_DEFAULT);
        if (hFile < 0)
        {
            fprintf(stderr,
                    "ERROR: Opening file %s failed! %s.\n",
                    pcFileData,
                    strerror(errno));
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }

        /* open the dataset, and get the dataspace */
        hDataset = H5Dopen(hFile,
                           YAPP_HDF5_DYNSPEC_GROUP YAPP_HDF5_DYNSPEC_DATASET,
                           H5P_DEFAULT);
        hDataspace = H5Dget_space(hDataset);
    }
    else
    {
        g_pFData = fopen(pcFileData, "r");
        if (NULL == g_pFData)
        {
            (void) fprintf(stderr,
                           "ERROR: Opening file %s failed! %s.\n",
                           pcFileData,
                           strerror(errno));
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
    }

    /* allocate memory for the buffer, based on the number of channels and time
       samples */
    g_pfBuf = (float *) YAPP_Malloc((size_t) stYUM.iNumChans * iBlockSize,
                                    sizeof(float),
                                    YAPP_FALSE);
    if (NULL == g_pfBuf)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            (void) H5Sclose(hDataspace);
            (void) H5Dclose(hDataset);
            (void) H5Fclose(hFile);
        }
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    if (1 == iNumReads)
    {
        cIsLastBlock = YAPP_TRUE;
    }

    if ((YAPP_FORMAT_FIL == iFormat) || (YAPP_FORMAT_DTS_TIM == iFormat))
    {
        /* skip the header */
        (void) fseek(g_pFData, (long) stYUM.iHeaderLen, SEEK_SET);
        /* skip data, if any are to be skipped */
        (void) fseek(g_pFData, lBytesToSkip, SEEK_CUR);
    }
    else if (iFormat != YAPP_FORMAT_HDF5)
    {
        /* skip data, if any are to be skipped */
        (void) fseek(g_pFData, lBytesToSkip, SEEK_SET);
    }
    else
    {
        if (lBytesToSkip != 0)
        {
            (void) printf("WARNING: Skipping data not supported for HDF5!\n");
        }
    }

    /* open the PGPLOT graphics device */
    g_iPGDev = cpgopen(PG_DEV);
    if (g_iPGDev <= 0)
    {
        (void) fprintf(stderr,
                       "ERROR: Opening graphics device %s failed!\n",
                       PG_DEV);
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            (void) H5Sclose(hDataspace);
            (void) H5Dclose(hDataset);
            (void) H5Fclose(hFile);
        }
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    /* set the background colour to white and the foreground colour to
       black, if user requires so */
    if (YAPP_TRUE == iInvCols)
    {
        cpgscr(0, 1.0, 1.0, 1.0);
        cpgscr(1, 0.0, 0.0, 0.0);
    }

    /* set character height */
    cpgsch(PG_CH);

    /* set up the plot's X-axis */
    g_pfXAxis = (float *) YAPP_Malloc(iBlockSize,
                                      sizeof(float),
                                      YAPP_TRUE);
    if (NULL == g_pfXAxis)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation for X-axis failed! %s!\n",
                       strerror(errno));
        cpgclos();
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            (void) H5Sclose(hDataspace);
            (void) H5Dclose(hDataset);
            (void) H5Fclose(hFile);
        }
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    g_pfXAxisOld = (float *) YAPP_Malloc(iBlockSize,
                                         sizeof(float),
                                         YAPP_FALSE);
    if (NULL == g_pfXAxisOld)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation for X-axis failed! %s!\n",
                       strerror(errno));
        cpgclos();
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            (void) H5Sclose(hDataspace);
            (void) H5Dclose(hDataset);
            (void) H5Fclose(hFile);
        }
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    if (!((YAPP_FORMAT_DTS_TIM == iFormat)
          || (YAPP_FORMAT_DTS_DAT == iFormat)
          || (YAPP_FORMAT_DTS_DDS == iFormat)))
    {
        /* set up the image plot's Y-axis (frequency) */
        g_pfYAxis = (float *) YAPP_Malloc(stYUM.iNumChans,
                                          sizeof(float),
                                          YAPP_FALSE);
        if (NULL == g_pfYAxis)
        {
            (void) fprintf(stderr,
                           "ERROR: Memory allocation for Y-axis failed! %s!\n",
                           strerror(errno));
            if (YAPP_FORMAT_HDF5 == iFormat)
            {
                (void) H5Sclose(hDataspace);
                (void) H5Dclose(hDataset);
                (void) H5Fclose(hFile);
            }
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
        if (stYUM.cIsBandFlipped)
        {
            for (i = 0; i < stYUM.iNumChans; ++i)
            {
                g_pfYAxis[i] = stYUM.fFMax - i * stYUM.fChanBW;
            }
        }
        else
        {
            for (i = 0; i < stYUM.iNumChans; ++i)
            {
                g_pfYAxis[i] = stYUM.fFMin + i * stYUM.fChanBW;
            }
        }
    }

    /* allocate memory for the cpgimag() plotting buffer */
    g_pfPlotBuf = (float *) YAPP_Malloc((stYUM.iNumChans * iBlockSize),
                                        sizeof(float),
                                        YAPP_FALSE);
    if (NULL == g_pfPlotBuf)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation for plot buffer failed! "
                       "%s!\n",
                       strerror(errno));
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            (void) H5Sclose(hDataspace);
            (void) H5Dclose(hDataset);
            (void) H5Fclose(hFile);
        }
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    if (dPeriod != 0.0)
    {
        /* compute the phase difference between successive samples */
        dMinPhaseDiff = (stYUM.dTSamp / dPeriod);
    }

    if (cShowBandpass)
    {
        /* allocate memory for the bandpass */
        g_pfBandpass = (float *) YAPP_Malloc(stYUM.iNumChans,
                                             sizeof(float),
                                             YAPP_TRUE);
        if (NULL == g_pfBandpass)
        {
            (void) fprintf(stderr,
                           "ERROR: Memory allocation for bandpass failed! "
                           "%s!\n",
                           strerror(errno));
            if (YAPP_FORMAT_HDF5 == iFormat)
            {
                (void) H5Sclose(hDataspace);
                (void) H5Dclose(hDataset);
                (void) H5Fclose(hFile);
            }
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
    }

    if (YAPP_FORMAT_HDF5 == iFormat)
    {
        switch (stYUM.iNumBits)
        {
            case YAPP_SAMPSIZE_8:
                hType = H5T_STD_I8LE;
                break;

            case YAPP_SAMPSIZE_16:
                hType = H5T_STD_I16LE;
                break;

            case YAPP_SAMPSIZE_32:
                hType = H5T_IEEE_F32LE;
                break;

            default:
                /* we don't expect this */
                assert ((YAPP_SAMPSIZE_8 == stYUM.iNumBits)
                        || (YAPP_SAMPSIZE_16 == stYUM.iNumBits)
                        || (YAPP_SAMPSIZE_32 == stYUM.iNumBits));
                return YAPP_RET_ERROR;
        }

        hMemDims[0] = stYUM.iNumChans;
        if (1 == iNumReads)
        {
            /* there is only one read */
            hMemDims[1] = stYUM.iTimeSamps;
        }
        else
        {
            hMemDims[1] = iTotSampsPerBlock / stYUM.iNumChans;
        }
        hMemDataspace = H5Screate_simple(YAPP_HDF5_DYNSPEC_RANK,
                                         hMemDims,
                                         NULL);

        /* define stride, count, and block */
        hOffset[0] = 0;
        hOffset[1] = 0;
        hCount[0] = stYUM.iNumChans;
        if (1 == iNumReads)
        {
            /* there is only one read */
            hCount[1] = stYUM.iTimeSamps;
        }
        else
        {
            hCount[1] = iTotSampsPerBlock / stYUM.iNumChans;
        }
    }

    while (iNumReads > 0)
    {
        /* read data */
        (void) printf("\rReading data block %d.", iReadBlockCount);
        (void) fflush(stdout);
        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            iReadItems = YAPP_ReadHDF5Data(hDataspace,
                                           hDataset,
                                           hOffset,
                                           hCount,
                                           hMemDataspace,
                                           hType,
                                           g_pfBuf,
                                           stYUM.fSampSize,
                                           iTotSampsPerBlock);
            if (YAPP_RET_ERROR == iReadItems)
            {
                (void) fprintf(stderr, "ERROR: Reading data failed!\n");
                (void) H5Sclose(hMemDataspace);
                (void) H5Dclose(hDataset);
                (void) H5Fclose(hFile);
                YAPP_CleanUp();
                return YAPP_RET_ERROR;
            }
        }
        else
        {
            iReadItems = YAPP_ReadData(g_pFData,
                                       g_pfBuf,
                                       stYUM.fSampSize,
                                       iTotSampsPerBlock);
            if (YAPP_RET_ERROR == iReadItems)
            {
                (void) fprintf(stderr, "ERROR: Reading data failed!\n");
                YAPP_CleanUp();
                return YAPP_RET_ERROR;
            }
        }
        --iNumReads;
        ++iReadBlockCount;

        if (YAPP_FORMAT_HDF5 == iFormat)
        {
            /* set offset for next copy*/
            hOffset[1] += hCount[1];
            if (1 == iNumReads)                 /* last-but-one block */
            {
                hCount[1] = stYUM.iTimeSamps - hOffset[1];
                hMemDims[1] = hCount[1];
                (void) H5Sclose(hMemDataspace);
                hMemDataspace = H5Screate_simple(YAPP_HDF5_DYNSPEC_RANK,
                                hMemDims,
                                NULL);
            }
        }

        if ((iReadItems < iTotSampsPerBlock)    /* usually, the last block */
            || (0 == iNumReads))                /* definitely the last block */
        {
            iDiff = (stYUM.iNumChans * iBlockSize) - iReadItems;

            /* reset remaining elements to '\0' */
            (void) memset((g_pfBuf + iReadItems),
                          '\0',
                          (sizeof(float) * iDiff));
        }
        else if (cIsLastBlock)  /* usually, when user has requested proc. time */
        {
            iDiff = (iBlockSize - (iTimeSampsToProc % iBlockSize))
                    * stYUM.iNumChans;

            /* reset remaining elements to '\0' */
            (void) memset((g_pfBuf + ((iTimeSampsToProc % iBlockSize)
                                      * stYUM.iNumChans)),
                          '\0',
                          (sizeof(float) * iDiff));
            /* TODO: .spec files will still process these trailing zeros */
        }

        /* calculate the number of time samples in the block - this may not
           be iBlockSize for the last block, and should be iBlockSize for
           all other blocks */
        iNumSamps = iReadItems / stYUM.iNumChans;

        if (YAPP_FORMAT_SPEC == iFormat)
        {
            /* flag bad time sections, and if required, normalise within the
               beam flip time section and perform gain correction */
            for (i = 0; i < iNumSamps; ++i)
            {
                if ((dTNow >= (*stYUM.padBadTimes)[iBadTimeSect][BADTIME_BEG])
                    && (dTNow <= (*stYUM.padBadTimes)[iBadTimeSect][BADTIME_END]))
                {
                    cIsInBadTimeRange = YAPP_TRUE;
                    g_pcIsTimeGood[((iReadBlockCount-1)*iBlockSize)+i]
                        = YAPP_FALSE;
                }

                if ((YAPP_TRUE == cIsInBadTimeRange)
                    && (dTNow > (*stYUM.padBadTimes)[iBadTimeSect][BADTIME_END]))
                {
                    cIsInBadTimeRange = YAPP_FALSE;
                    ++iBadTimeSect;
                }

                /* get the beam flip time section corresponding to this
                   sample */
                if (dTNow > dTNextBF)
                {
                    dTNextBF += stYUM.dTBFInt;

                    ++iTimeSect;
                    if (iTimeSect >= stYUM.iBFTimeSects)
                    {
                        (void) fprintf(stderr,
                                       "ERROR: Beam flip time section anomaly "
                                       "detected!\n");
                        YAPP_CleanUp();
                        return YAPP_RET_ERROR;
                    }
                }

                pfTimeSectGain = stYUM.pfBFGain + (iTimeSect * stYUM.iNumChans);
                pfSpectrum = g_pfBuf + i * stYUM.iNumChans;
                for (j = 0; j < stYUM.iNumChans; ++j)
                {
                    if (stYUM.pcIsChanGood[j])
                    {
                        if (fClipLevel != 0.0)
                        {
                            if (pfSpectrum[j] > ((dNumSigmas + fClipLevel)
                                                 * fNoiseRMS))
                            {
                                pfSpectrum[j] = (dNumSigmas + fClipLevel)
                                                * fNoiseRMS;
                            }
                            else if (pfSpectrum[j] < -((dNumSigmas + fClipLevel)
                                                       * fNoiseRMS))
                            {
                                pfSpectrum[j] = -((dNumSigmas + fClipLevel)
                                                  * fNoiseRMS);
                            }
                        }

                        pfSpectrum[j] = (pfSpectrum[j]
                                         / stYUM.pfBFTimeSectMean[iTimeSect])
                                        - pfTimeSectGain[j];
                    }
                    else    /* remove bad channels */
                    {
                        pfSpectrum[j] = 0.0;
                    }
                }

                dTNow += dTSampInSec;   /* in s */
            }
        }
        else if (YAPP_FORMAT_FIL == iFormat)
        {
            /* perform clipping, if required */
            for (i = 0; i < iNumSamps; ++i)
            {
                pfSpectrum = g_pfBuf + i * stYUM.iNumChans;
                for (j = 0; j < stYUM.iNumChans; ++j)
                {
                    if (fClipLevel != 0.0)
                    {
                        if (pfSpectrum[j] > ((dNumSigmas + fClipLevel)
                                             * fNoiseRMS))
                        {
                            pfSpectrum[j] = (dNumSigmas + fClipLevel)
                                            * fNoiseRMS;
                        }
                        else if (pfSpectrum[j] < -((dNumSigmas + fClipLevel)
                                                   * fNoiseRMS))
                        {
                            pfSpectrum[j] = -((dNumSigmas + fClipLevel)
                                              * fNoiseRMS);
                        }
                    }
                }
            }
        }

        for (i = 0; i < iBlockSize; ++i)
        {
            g_pfXAxisOld[i] = g_pfXAxis[i];
            g_pfXAxis[i] = (float) (dDataSkipTime
                                    + (((iReadBlockCount - 1)
                                        * iBlockSize
                                        * dTSampInSec)
                                       + (i * dTSampInSec)));
        }

        if (!((YAPP_FORMAT_DTS_TIM == iFormat)
              || (YAPP_FORMAT_DTS_DAT == iFormat)
              || (YAPP_FORMAT_DTS_DDS == iFormat)))
        {
            pfSpectrum = g_pfBuf;
            fDataMin = pfSpectrum[0];
            fDataMax = pfSpectrum[0];
            for (j = 0; j < iBlockSize; ++j)
            {
                pfSpectrum = g_pfBuf + j * stYUM.iNumChans;
                for (k = 0; k < stYUM.iNumChans; ++k)
                {
                    if (pfSpectrum[k] < fDataMin)
                    {
                        fDataMin = pfSpectrum[k];
                    }
                    if (pfSpectrum[k] > fDataMax)
                    {
                        fDataMax = pfSpectrum[k];
                    }
                }
            }

            /* get the transpose of the two-dimensional array */
            i = 0;
            j = 0;
            k = 0;
            for (l = 0; l < iBlockSize; ++l)
            {
                pfSpectrum = g_pfBuf + l * stYUM.iNumChans;
                for (m = 0; m < stYUM.iNumChans; ++m)
                {
                    j = k + i * iBlockSize;
                    g_pfPlotBuf[j] = pfSpectrum[m];
                    if (cShowBandpass)
                    {
                        /* construct the bandpass */
                        g_pfBandpass[m] += pfSpectrum[m];
                    }
                    ++i;
                }
                i = 0;
                ++k;
            }

            /* erase the previous x-axis */
            if (!cIsFirst && !cIsNonInteractive)   /* kludge */
            {
                cpgsvp(PG_2D_VP_ML, PG_2D_VP_MR, PG_2D_VP_MB, PG_2D_VP_MT);
                cpgswin(g_pfXAxisOld[0],
                        g_pfXAxisOld[iBlockSize-1],
                        g_pfYAxis[0],
                        g_pfYAxis[stYUM.iNumChans-1]);
            }
            cpgsci(0);      /* background */
            cpgaxis("N",
                    g_pfXAxisOld[0], g_pfYAxis[0],
                    g_pfXAxisOld[iBlockSize-1], g_pfYAxis[0],
                    g_pfXAxisOld[0], g_pfXAxisOld[iBlockSize-1],
                    0.0,
                    0,
                    0.5,
                    0.0,
                    0.5,
                    0.5,
                    0);
            cpgbox("CST", 0.0, 0, "CST", 0.0, 0);
            cIsFirst = YAPP_FALSE;
            cpgsci(PG_CI_DEF);
            Plot2D(g_pfPlotBuf, fDataMin, fDataMax,
                   g_pfXAxis, iBlockSize, dTSampInSec,
                   g_pfYAxis, stYUM.iNumChans, stYUM.fChanBW,
                   "Time - Start Time (s)", "Frequency (MHz)", "Dynamic Spectrum",
                   iColourMap);
        }
        else
        {
            /* erase just before plotting, to reduce flicker */
            cpgeras();
            cpgsvp(PG_VP_ML, PG_VP_MR, PG_VP_MB, PG_VP_MT);
            /* set minimum and maximum according to intrinsic values and clip
               level */
            if (cUseAbsScale)
            {
                if (fClipLevel != 0.0)
                {
                    fDataMin = stYUM.fMean - (3 * stYUM.fRMS);
                    fDataMax = stYUM.fMean + (fClipLevel * stYUM.fRMS);
                }
                else
                {
                    fDataMin = stYUM.fMin;
                    fDataMax = stYUM.fMax;
                }
            }
            else
            {
                pfSpectrum = g_pfBuf;
                fDataMin = pfSpectrum[0];
                fDataMax = pfSpectrum[0];
                for (j = 0; j < iBlockSize; ++j)
                {
                    pfSpectrum = g_pfBuf + j * stYUM.iNumChans;
                    for (k = 0; k < stYUM.iNumChans; ++k)
                    {
                        if (pfSpectrum[k] < fDataMin)
                        {
                            fDataMin = pfSpectrum[k];
                        }
                        if (pfSpectrum[k] > fDataMax)
                        {
                            fDataMax = pfSpectrum[k];
                        }
                    }
                }
            }
            cpgswin(g_pfXAxis[0],
                    g_pfXAxis[iBlockSize-1],
                    fDataMin,
                    fDataMax);
            cpglab("Time - Start Time (s)", "Power (arbitrary units)", "Time Series");
            cpgbox("BCNST", 0.0, 0, "BCNST", 0.0, 0);
            cpgsci(PG_CI_PLOT);
            cpgline(iBlockSize, g_pfXAxis, g_pfBuf);
            cpgsci(PG_CI_DEF);
        }

        if (dPeriod != 0.0)
        {
            cpgsci(7);
            for (i = 0; i < iNumSamps; ++i)
            {
                /* compute the phase */
                dPhase = (double) lSampCount * (stYUM.dTSamp / dPeriod);
                dPhase = dPhase - floor(dPhase);
                if (fabs(dPhase - dStartPhase) < dMinPhaseDiff)
                {
                    cpgerry(1, &g_pfXAxis[i], &fDataMax, &fDataMin, 0.0);
                }
                ++lSampCount;
            }
            cpgsci(PG_CI_DEF);
        }

        /* display the plot number */
        /* TODO: bug - in maximized window, plot not proper  */
        (void) sprintf(acLabel, "%d / %d", iReadBlockCount, iTotNumReads);
        cpgmtxt("T", -1.5, 0.99, 1.0, acLabel);

        if (!(cIsLastBlock))
        {
            if (!(cIsNonInteractive))
            {
                /* draw the 'next' and 'exit' buttons */
                cpgsvp(PG_VP_BUT_ML, PG_VP_BUT_MR, PG_VP_BUT_MB, PG_VP_BUT_MT);
                cpgswin(PG_BUT_L, PG_BUT_R, PG_BUT_B, PG_BUT_T);
                cpgsci(PG_BUT_FILLCOL); /* set the fill colour */
                cpgrect(PG_BUTNEXT_L, PG_BUTNEXT_R, PG_BUTNEXT_B, PG_BUTNEXT_T);
                cpgrect(PG_BUTEXIT_L, PG_BUTEXIT_R, PG_BUTEXIT_B, PG_BUTEXIT_T);
                cpgsci(0);  /* set colour index to background */
                cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");

                fButX = (PG_BUTNEXT_R - PG_BUTNEXT_L) / 2;
                fButY = (PG_BUTNEXT_T - PG_BUTNEXT_B) / 2;

                while (YAPP_TRUE)
                {
                    iRet = cpgcurs(&fButX, &fButY, &cCurChar);
                    if (0 == iRet)
                    {
                        (void) fprintf(stderr,
                                       "WARNING: "
                                       "Reading cursor parameters failed!\n");
                        break;
                    }

                    if (((fButX >= PG_BUTNEXT_L) && (fButX <= PG_BUTNEXT_R))
                        && ((fButY >= PG_BUTNEXT_B) && (fButY <= PG_BUTNEXT_T)))
                    {
                        /* animate button click */
                        cpgsci(PG_BUT_FILLCOL);
                        cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                        cpgsci(0);  /* set colour index to white */
                        cpgtext(PG_BUTNEXT_CL_TEXT_L, PG_BUTNEXT_CL_TEXT_B, "Next");
                        (void) usleep(PG_BUT_CL_SLEEP);
                        cpgsci(PG_BUT_FILLCOL); /* set colour index to fill
                                                   colour */
                        cpgtext(PG_BUTNEXT_CL_TEXT_L, PG_BUTNEXT_CL_TEXT_B, "Next");
                        cpgsci(0);  /* set colour index to white */
                        cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                        cpgsci(PG_CI_DEF);  /* reset colour index to black */
                        (void) usleep(PG_BUT_CL_SLEEP);

                        break;
                    }
                    else if (((fButX >= PG_BUTEXIT_L) && (fButX <= PG_BUTEXIT_R))
                        && ((fButY >= PG_BUTEXIT_B) && (fButY <= PG_BUTEXIT_T)))
                    {
                        /* animate button click */
                        cpgsci(PG_BUT_FILLCOL);
                        cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");
                        cpgsci(0);  /* set colour index to white */
                        cpgtext(PG_BUTEXIT_CL_TEXT_L, PG_BUTEXIT_CL_TEXT_B, "Exit");
                        (void) usleep(PG_BUT_CL_SLEEP);
                        cpgsci(PG_BUT_FILLCOL); /* set colour index to fill
                                                   colour */
                        cpgtext(PG_BUTEXIT_CL_TEXT_L, PG_BUTEXIT_CL_TEXT_B, "Exit");
                        cpgsci(0);  /* set colour index to white */
                        cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");
                        cpgsci(PG_CI_DEF);  /* reset colour index to black */
                        (void) usleep(PG_BUT_CL_SLEEP);

                        cpgclos();
                        if (YAPP_FORMAT_HDF5 == iFormat)
                        {
                            (void) H5Sclose(hMemDataspace);
                            (void) H5Sclose(hDataspace);
                            (void) H5Dclose(hDataset);
                            (void) H5Fclose(hFile);
                        }
                        YAPP_CleanUp();
                        return YAPP_RET_SUCCESS;
                    }
                }
            }
            else
            {
                /* pause before erasing */
                (void) usleep(PG_PLOT_SLEEP);
            }
        }

        if (1 == iNumReads)
        {
            cIsLastBlock = YAPP_TRUE;
        }
    }

    (void) printf("DONE!\n");

    cpgclos();
    if (YAPP_FORMAT_HDF5 == iFormat)
    {
        (void) H5Sclose(hMemDataspace);
        (void) H5Sclose(hDataspace);
        (void) H5Dclose(hDataset);
        (void) H5Fclose(hFile);
    }
    YAPP_CleanUp();

    return YAPP_RET_SUCCESS;
}

/*
 * Prints usage information
 */
void PrintUsage(const char *pcProgName)
{
    (void) printf("Usage: %s [options] <data-file>\n",
                  pcProgName);
    (void) printf("    -h  --help                          ");
    (void) printf("Display this usage information\n");
    (void) printf("    -s  --skip <time>                   ");
    (void) printf("The length of data in seconds, to be\n");
    (void) printf("                                        ");
    (void) printf("skipped\n");
    (void) printf("    -p  --proc <time>                   ");
    (void) printf("The length of data in seconds, to be\n");
    (void) printf("                                        ");
    (void) printf("processed\n");
    (void) printf("                                        ");
    (void) printf("(default is all)\n");
    (void) printf("    -n  --nsamp <samples>               ");
    (void) printf("Number of samples read in one block\n");
    (void) printf("                                        ");
    (void) printf("(default is 4096 samples)\n");
    (void) printf("    -b  --nband <bands>                 ");
    (void) printf("Number of bands for spliced filterbank\n");
    (void) printf("                                        ");
    (void) printf("files\n");
    (void) printf("    -c  --clip-level <level>            ");
    (void) printf("Number of sigmas above threshold; will\n");
    (void) printf("                                        ");
    (void) printf("clip anything above this level\n");
    (void) printf("    -a  --no-abs-scale                  ");
    (void) printf("Use relative scale for plotting per\n");
    (void) printf("                                        ");
    (void) printf("block\n");
    (void) printf("    -d  --show-bandpass                 ");
    (void) printf("Show the bandpass for each block\n");
    (void) printf("    -t  --period <period>               ");
    (void) printf("Period of the pulsar in ms\n");
    (void) printf("    -r  --phase <phase>                 ");
    (void) printf("Phase of the first pulse with respect\n");
    (void) printf("                                        ");
    (void) printf("to the first sample\n");
    (void) printf("    -m  --colour-map <name>             ");
    (void) printf("Colour map for plotting\n");
    (void) printf("                                        ");
    (void) printf("(default is 'jet')\n");
    (void) printf("    -i  --invert                        ");
    (void) printf("Invert background and foreground\n");
    (void) printf("                                        ");
    (void) printf("colours in plots\n");
    (void) printf("    -e  --non-interactive               ");
    (void) printf("Run in non-interactive mode\n");
    (void) printf("    -v  --version                       ");
    (void) printf("Display the version\n");

    return;
}

