/*
 * @file yapp_add.c
 * Program to coherently add dedispersed time series data for different
 *  frequency bands.
 *
 * @verbatim
 * Usage: yapp_add [options] <data-file-maxfreq> ... <data-file-minfreq>
 *     -h  --help                           Display this usage information
 *     -n  --nsamp <samples>                Number of samples read in one block
 *                                          (default is 4096 samples)
 *     -g  --graphics                       Turn on plotting
 *     -i  --invert                         Invert the background and foreground
 *                                          colours in plots
 *     -e  --non-interactive                Run in non-interactive mode
 *     -v  --version                        Display the version @endverbatim
 *
 * @author Jayanth Chennamangalam
 * @date 2013.03.24
 */

#include "yapp.h"
#include "yapp_sigproc.h"   /* for SIGPROC filterbank file format support */

int CalcOffset(float fFMax, float fFMin, double dTSamp, double dDM);

/**
 * The build version string, maintained in the file version.c, which is
 * generated by makever.c.
 */
extern const char *g_pcVersion;

/* PGPLOT device ID */
extern int g_iPGDev;

/* the following are global only to enable cleaning up in case of abnormal
   termination, such as those triggered by SIGINT or SIGTERM */
float **g_ppfBuf = NULL;
float *g_pfOutBuf = NULL;
float *g_pfXAxis = NULL;

int main(int argc, char *argv[])
{
    FILE **ppFIn = NULL;
    FILE *pFOut = NULL;
    char *pcFileOut = NULL;
    int iNumBands = 0;
    char acFileOut[LEN_GENSTRING] = {0};
    int iFormat = DEF_FORMAT;
    YUM_t stYUM = {{0}};
    float *pafMaxFreq = NULL;
    float *pafMinFreq = NULL;
    int iBlockSize = DEF_SIZE_BLOCK;
    int iTotSampsPerBlock = 0;  /* iBlockSize */
    double dTSampInSec = 0.0;   /* holds sampling time in s */
    int iNumReads = 0;
    int iTotNumReads = 0;
    int iReadBlockCount = 0;
    char cIsLastBlock = YAPP_FALSE;
    int iRet = YAPP_RET_SUCCESS;
    float fDataMin = 0.0;
    float fDataMax = 0.0;
    int iReadItems = 0;
    float fButX = 0.0;
    float fButY = 0.0;
    char cCurChar = 0;
    int iNumSamps = 0;
    int iDiff = 0;
    float fTemp = 0.0;
    int iTemp = 0;
    FILE *pFTemp = NULL;
    int *paiOffset = NULL;
    int i = 0;
    int j = 0;
    char acLabel[LEN_GENSTRING] = {0};
    char cHasGraphics = YAPP_FALSE;
    int iInvCols = YAPP_FALSE;
    char cIsNonInteractive = YAPP_FALSE;
    const char *pcProgName = NULL;
    int iNextOpt = 0;
    /* valid short options */
    const char* const pcOptsShort = "hn:giev";
    /* valid long options */
    const struct option stOptsLong[] = {
        { "help",                   0, NULL, 'h' },
        { "nsamp",                  1, NULL, 'n' },
        { "graphics",               0, NULL, 'g' },
        { "invert",                 0, NULL, 'i' },
        { "non-interactive",        0, NULL, 'e' },
        { "version",                0, NULL, 'v' },
        { NULL,                     0, NULL, 0   }
    };

    /* get the filename of the program from the argument list */
    pcProgName = argv[0];

    /* parse the input */
    do
    {
        iNextOpt = getopt_long(argc, argv, pcOptsShort, stOptsLong, NULL);
        switch (iNextOpt)
        {
            case 'h':   /* -h or --help */
                /* print usage info and terminate */
                PrintUsage(pcProgName);
                return YAPP_RET_SUCCESS;

            case 'n':   /* -n or --nsamp */
                /* set option */
                iBlockSize = atoi(optarg);
                /* validate - PGPLOT does not like iBlockSize = 1 */
                if (iBlockSize < 2)
                {
                    (void) fprintf(stderr,
                                   "ERROR: Number of samples must be > 1!\n");
                    PrintUsage(pcProgName);
                    return YAPP_RET_ERROR;
                }
                break;

            case 'g':   /* -g or --graphics */
                /* set option */
                cHasGraphics = YAPP_TRUE;
                break;

            case 'i':  /* -i or --invert */
                /* set option */
                iInvCols = YAPP_TRUE;
                break;

            case 'e':  /* -e or --non-interactive */
                /* set option */
                cIsNonInteractive = YAPP_TRUE;
                break;

            case 'v':   /* -v or --version */
                /* display the version */
                (void) printf("%s\n", g_pcVersion);
                return YAPP_RET_SUCCESS;

            case '?':   /* user specified an invalid option */
                /* print usage info and terminate with error */
                (void) fprintf(stderr, "ERROR: Invalid option!\n");
                PrintUsage(pcProgName);
                return YAPP_RET_ERROR;

            case -1:    /* done with options */
                break;

            default:    /* unexpected */
                assert(0);
        }
    } while (iNextOpt != -1);

    /* no arguments */
    if (argc <= optind)
    {
        (void) fprintf(stderr, "ERROR: Input file not specified!\n");
        PrintUsage(pcProgName);
        return YAPP_RET_ERROR;
    }

    /* only one file - no need to add */
    iNumBands = argc - optind;
    if (iNumBands == 1)
    {
        (void) fprintf(stderr, "ERROR: Only one input file given!\n");
        PrintUsage(pcProgName);
        return YAPP_RET_ERROR;
    }

    /* register the signal-handling function */
    iRet = YAPP_RegisterSignalHandlers();
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr,
                       "ERROR: Handler registration failed!\n");
        return YAPP_RET_ERROR;
    }

    /* user input validation - check the file type for all input files */
    for (i = optind; i < argc; ++i)
    {
        /* determine the file type */
        iFormat = YAPP_GetFileType(argv[i]);
        if (YAPP_RET_ERROR == iFormat)
        {
            (void) fprintf(stderr,
                           "ERROR: File type determination failed!\n");
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
        if (iFormat != YAPP_FORMAT_DTS_TIM)
        {
            (void) fprintf(stderr,
                           "ERROR: Invalid file type!\n");
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
    }

    /* read metadata */
    /* NOTE: it is assumed that all files correspond to a single observation.
             the only information taken from all files except the last one is
             the highest frequency. common metadata is read from the last
             file */
    /* allocate memory for the frequency array */
    pafMaxFreq = (float *) YAPP_Malloc((size_t) iNumBands,
                                    sizeof(float),
                                    YAPP_FALSE);
    if (NULL == pafMaxFreq)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    pafMinFreq = (float *) YAPP_Malloc((size_t) iNumBands,
                                    sizeof(float),
                                    YAPP_FALSE);
    if (NULL == pafMinFreq)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    /* allocate memory for the offsets array */
    paiOffset = (int *) YAPP_Malloc((size_t) iNumBands,
                                    sizeof(int),
                                    YAPP_FALSE);
    if (NULL == paiOffset)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    for (i = optind; i < argc; ++i)
    {
        (void) memset(&stYUM, '\0', sizeof(YUM_t));
        iRet = YAPP_ReadMetadata(argv[i], iFormat, &stYUM);
        if (iRet != YAPP_RET_SUCCESS)
        {
            (void) fprintf(stderr,
                           "ERROR: Reading metadata failed for file %s!\n",
                           argv[i]);
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
        pafMaxFreq[i-optind] = stYUM.fFMax;
        pafMinFreq[i-optind] = stYUM.fFMin;
    }
    /* calculate the maximum offsets in each band, relative to the highest
       frequency one */
    paiOffset[0] = 0;
    for (i = 1; i < iNumBands; ++i)
    {
    #if 0
        /* basic check to see if the files are in proper frequency order */
        /* NOTE: this program supports frequency overlap, so compare with
                 pafMaxFreq[i-1] instead of pafMinFreq[i-1] */
        if (stYUM.fFMax > pafMaxFreq[i-1])
        {
            (void) fprintf(stderr,
                           "ERROR: Files not in correct order!\n");
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
        #endif
        paiOffset[i] = CalcOffset(pafMaxFreq[0],
                                  pafMaxFreq[i],
                                  stYUM.dTSamp,
                                  stYUM.dDM);
    }

    /* convert sampling interval to seconds */
    dTSampInSec = stYUM.dTSamp / 1e3;

    iNumReads = (int) ceilf(((float) stYUM.iTimeSamps) / iBlockSize);
    iTotNumReads = iNumReads;

    /* optimisation - store some commonly used values in variables */
    iTotSampsPerBlock = iBlockSize;

    /* open the time series data files for reading */
    /* allocate memory for the file pointer array */
    ppFIn = (FILE **) YAPP_Malloc((size_t) iNumBands,
                                  sizeof(FILE *),
                                  YAPP_FALSE);
    if (NULL == ppFIn)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    for (i = optind; i < argc; ++i)
    {
        ppFIn[i-optind] = fopen(argv[i], "r");
        if (NULL == ppFIn[i-optind])
        {
            (void) fprintf(stderr,
                           "ERROR: Opening file %s failed! %s.\n",
                           argv[i],
                           strerror(errno));
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }

        /* skip the header */
        (void) fseek(ppFIn[i-optind], (long) stYUM.iHeaderLen, SEEK_SET);

        /* skip the offsets */
        (void) fseek(ppFIn[i-optind],
                     (long) (paiOffset[i-optind] * stYUM.fSampSize),
                     SEEK_CUR);
    }

/* TODO: sorting bug */
#if 1
    /* sort the input files, maximum and minimum frequency arrays, and offset
       array in descending frequency order */
    for (i = 0; i < iNumBands; ++i)
    {
        for (j = i; j < iNumBands; ++j)
        {
            if (pafMaxFreq[j] > pafMaxFreq[i])
            {
                /* swap maximum frequencies */
                fTemp = pafMaxFreq[i];
                pafMaxFreq[i] = pafMaxFreq[j];
                pafMaxFreq[j] = fTemp;

                /* swap minimum frequencies */
                fTemp = pafMinFreq[i];
                pafMinFreq[i] = pafMinFreq[j];
                pafMinFreq[j] = fTemp;

                /* swap offsets */
                iTemp = paiOffset[i];
                paiOffset[i] = paiOffset[j];
                paiOffset[j] = iTemp;

                /* swap file handles */
                pFTemp = ppFIn[i];
                ppFIn[i] = ppFIn[j];
                ppFIn[j] = pFTemp;
            }
        }
    }
#endif
    /* allocate memory for the buffer pointer array */
    g_ppfBuf = (float **) YAPP_Malloc((size_t) iNumBands,
                                      sizeof(float *),
                                      YAPP_FALSE);
    if (NULL == g_ppfBuf)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation failed! %s!\n",
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }
    /* allocate memory for the buffer */
    for (i = 0; i < iNumBands; ++i)
    {
        g_ppfBuf[i] = (float *) YAPP_Malloc((size_t) iBlockSize,
                                            sizeof(float),
                                            YAPP_FALSE);
        if (NULL == g_ppfBuf[i])
        {
            (void) fprintf(stderr,
                           "ERROR: Memory allocation failed! %s!\n",
                           strerror(errno));
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
    }

    if (1 == iNumReads)
    {
        cIsLastBlock = YAPP_TRUE;
    }

    /* open the time series data file for writing */
    pcFileOut = YAPP_GetFilenameFromPath(argv[optind]);
    (void) sprintf(acFileOut,
                   "%s.%s%s",
                   pcFileOut,
                   INFIX_ADD,
                   EXT_TIM);

    /* populate the YUM structure for output */
    stYUM.fFMax = pafMaxFreq[0];
    stYUM.fFMin = pafMinFreq[iNumBands-1];
    /* NOTE: min and max are centre frequencies of channels */
    stYUM.fBW = stYUM.fFMax - stYUM.fFMin + stYUM.fChanBW;
    /* spoof filterbank-related parameters so that YAPP_ReadSIGPROCHeader()
       will compute the minimum and maximum frequencies correctly for the
       output .tim file
       NOTE: the number of channels and channel bandwidth need to be modified
       here to preserve the min and max frequencies and bandwidth */
    /* TODO:  (ideal solution: use YAPP data format and convert to tim/dat
       at the end. */
    stYUM.iNumChans = (int) roundf(stYUM.fBW / stYUM.fChanBW);
    stYUM.fChanBW = stYUM.fBW / stYUM.iNumChans;
    //stYUM.iNumChans = 1;
    //stYUM.fChanBW = stYUM.fBW;
    //stYUM.cIsBandFlipped = YAPP_FALSE;
    /* write metadata to disk */
    iRet = YAPP_WriteMetadata(acFileOut, iFormat, stYUM);
    if (iRet != YAPP_RET_SUCCESS)
    {
        (void) fprintf(stderr,
                       "ERROR: Writing metadata failed for file %s!\n",
                       acFileOut);
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    /* open file for appending data */
    pFOut = fopen(acFileOut, "a");
    if (NULL == pFOut)
    {
        (void) fprintf(stderr,
                       "ERROR: Opening file %s failed! %s.\n",
                       acFileOut,
                       strerror(errno));
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    /* open the PGPLOT graphics device */
    if (cHasGraphics)
    {
        g_iPGDev = cpgopen(PG_DEV);
        if (g_iPGDev <= 0)
        {
            (void) fprintf(stderr,
                           "ERROR: Opening graphics device %s failed!\n",
                           PG_DEV);
            (void) fclose(pFOut);
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }

        /* set the background colour to white and the foreground colour to
           black, if user requires so */
        if (YAPP_TRUE == iInvCols)
        {
            cpgscr(0, 1.0, 1.0, 1.0);
            cpgscr(1, 0.0, 0.0, 0.0);
        }

        cpgsch(PG_CH);

        /* set up the plot's X-axis */
        g_pfXAxis = (float *) YAPP_Malloc(iBlockSize,
                                          sizeof(float),
                                          YAPP_FALSE);
        if (NULL == g_pfXAxis)
        {
            (void) fprintf(stderr,
                           "ERROR: Memory allocation for X-axis failed! %s!\n",
                           strerror(errno));
            (void) fclose(pFOut);
            YAPP_CleanUp();
            return YAPP_RET_ERROR;
        }
    }

    /* allocate memory for the accumulation buffer */
    g_pfOutBuf = (float *) YAPP_Malloc((size_t) iBlockSize,
                                       sizeof(float),
                                       YAPP_TRUE);
    if (NULL == g_pfOutBuf)
    {
        (void) fprintf(stderr,
                       "ERROR: Memory allocation for plot buffer failed! "
                       "%s!\n",
                       strerror(errno));
        (void) fclose(pFOut);
        YAPP_CleanUp();
        return YAPP_RET_ERROR;
    }

    while (iNumReads > 0)
    {
        /* read data */
        (void) printf("\rReading data block %d of %d.",
                      iReadBlockCount + 1,
                      iTotNumReads);
        (void) fflush(stdout);
        for (i = 0; i < iNumBands; ++i)
        {
            iReadItems = YAPP_ReadData(ppFIn[i],
                                       g_ppfBuf[i],
                                       stYUM.fSampSize,
                                       iTotSampsPerBlock);
            if (YAPP_RET_ERROR == iReadItems)
            {
                (void) fprintf(stderr, "ERROR: Reading data failed!\n");
                (void) fclose(pFOut);
                YAPP_CleanUp();
                return YAPP_RET_ERROR;
            }

            if (iReadItems < iTotSampsPerBlock)
            {
                iDiff = iBlockSize - iReadItems;

                /* reset remaining elements to '\0' */
                (void) memset((g_ppfBuf[0] + iReadItems),
                              '\0',
                              (sizeof(float) * iDiff));
            }

            /* calculate the number of time samples in the block - this may not
               be iBlockSize for the last block, and should be iBlockSize for
               all other blocks */
            iNumSamps = iReadItems;
        }
        --iNumReads;
        ++iReadBlockCount;

        /* zero the accumulator */
        (void) memset(g_pfOutBuf, '\0', sizeof(float) * iBlockSize);
        /* sum the time series */
        for (i = 0; i < iBlockSize; ++i)
        {
            for (j = 0; j < iNumBands; ++j)
            {
                g_pfOutBuf[i] += g_ppfBuf[j][i];
            }
        }

        /* write summed data to file */
        (void) fwrite(g_pfOutBuf,
                      sizeof(float),
                      (long) iNumSamps,
                      pFOut);

        if (cHasGraphics)
        {
            fDataMin = g_pfOutBuf[0];
            fDataMax = g_pfOutBuf[0];
            for (i = 0; i < iNumSamps; ++i)
            {
                if (g_pfOutBuf[i] < fDataMin)
                {
                    fDataMin = g_pfOutBuf[i];
                }
                if (g_pfOutBuf[i] > fDataMax)
                {
                    fDataMax = g_pfOutBuf[i];
                }
            }

            #ifdef DEBUG
            (void) printf("Minimum value of data             : %g\n",
                          fDataMin);
            (void) printf("Maximum value of data             : %g\n",
                          fDataMax);
            #endif

            /* erase just before plotting, to reduce flicker */
            cpgeras();
            for (i = 0; i < iBlockSize; ++i)
            {
                g_pfXAxis[i] = (float) (((iReadBlockCount - 1)
                                            * iBlockSize
                                            * dTSampInSec)
                                           + (i * dTSampInSec));
            }

            cpgsvp(PG_VP_ML, PG_VP_MR, PG_VP_MB, PG_VP_MT);
            cpgswin(g_pfXAxis[0],
                    g_pfXAxis[iBlockSize-1],
                    fDataMin,
                    fDataMax);
            cpglab("Time (s)", "", "");
            cpgbox("BCNST", 0.0, 0, "BCNST", 0.0, 0);
            cpgsci(PG_CI_PLOT);
            cpgline(iBlockSize, g_pfXAxis, g_pfOutBuf);
            cpgsci(PG_CI_DEF);

            /* display the plot number */
            /* TODO: bug - in maximized window, plot not proper  */
            (void) sprintf(acLabel, "%d / %d", iReadBlockCount, iTotNumReads);
            cpgmtxt("T", -1.5, 0.99, 1.0, acLabel);

            if (!(cIsLastBlock))
            {
                if (!(cIsNonInteractive))
                {
                    /* draw the 'next' and 'exit' buttons */
                    cpgsvp(PG_VP_BUT_ML, PG_VP_BUT_MR, PG_VP_BUT_MB, PG_VP_BUT_MT);
                    cpgswin(PG_BUT_L, PG_BUT_R, PG_BUT_B, PG_BUT_T);
                    cpgsci(PG_BUT_FILLCOL); /* set the fill colour */
                    cpgrect(PG_BUTNEXT_L, PG_BUTNEXT_R, PG_BUTNEXT_B, PG_BUTNEXT_T);
                    cpgrect(PG_BUTEXIT_L, PG_BUTEXIT_R, PG_BUTEXIT_B, PG_BUTEXIT_T);
                    cpgsci(0);  /* set colour index to white */
                    cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                    cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");

                    fButX = (PG_BUTNEXT_R - PG_BUTNEXT_L) / 2;
                    fButY = (PG_BUTNEXT_T - PG_BUTNEXT_B) / 2;

                    while (YAPP_TRUE)
                    {
                        iRet = cpgcurs(&fButX, &fButY, &cCurChar);
                        if (0 == iRet)
                        {
                            (void) fprintf(stderr,
                                           "WARNING: "
                                           "Reading cursor parameters failed!\n");
                            break;
                        }

                        if (((fButX >= PG_BUTNEXT_L) && (fButX <= PG_BUTNEXT_R))
                            && ((fButY >= PG_BUTNEXT_B) && (fButY <= PG_BUTNEXT_T)))
                        {
                            /* animate button click */
                            cpgsci(PG_BUT_FILLCOL);
                            cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                            cpgsci(0);  /* set colour index to white */
                            cpgtext(PG_BUTNEXT_CL_TEXT_L, PG_BUTNEXT_CL_TEXT_B, "Next");
                            (void) usleep(PG_BUT_CL_SLEEP);
                            cpgsci(PG_BUT_FILLCOL); /* set colour index to fill
                                                       colour */
                            cpgtext(PG_BUTNEXT_CL_TEXT_L, PG_BUTNEXT_CL_TEXT_B, "Next");
                            cpgsci(0);  /* set colour index to white */
                            cpgtext(PG_BUTNEXT_TEXT_L, PG_BUTNEXT_TEXT_B, "Next");
                            cpgsci(1);  /* reset colour index to black */
                            (void) usleep(PG_BUT_CL_SLEEP);

                            break;
                        }
                        else if (((fButX >= PG_BUTEXIT_L) && (fButX <= PG_BUTEXIT_R))
                            && ((fButY >= PG_BUTEXIT_B) && (fButY <= PG_BUTEXIT_T)))
                        {
                            /* animate button click */
                            cpgsci(PG_BUT_FILLCOL);
                            cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");
                            cpgsci(0);  /* set colour index to white */
                            cpgtext(PG_BUTEXIT_CL_TEXT_L, PG_BUTEXIT_CL_TEXT_B, "Exit");
                            (void) usleep(PG_BUT_CL_SLEEP);
                            cpgsci(PG_BUT_FILLCOL); /* set colour index to fill
                                                       colour */
                            cpgtext(PG_BUTEXIT_CL_TEXT_L, PG_BUTEXIT_CL_TEXT_B, "Exit");
                            cpgsci(0);  /* set colour index to white */
                            cpgtext(PG_BUTEXIT_TEXT_L, PG_BUTEXIT_TEXT_B, "Exit");
                            cpgsci(1);  /* reset colour index to black */
                            (void) usleep(PG_BUT_CL_SLEEP);

                            (void) fclose(pFOut);
                            YAPP_CleanUp();
                            return YAPP_RET_SUCCESS;
                        }
                    }
                }
                else
                {
                    /* pause before erasing */
                    (void) usleep(PG_PLOT_SLEEP);
                }
            }
        }

        if (1 == iNumReads)
        {
            cIsLastBlock = YAPP_TRUE;
        }
    }

    (void) printf("DONE!\n");

    (void) fclose(pFOut);
    YAPP_CleanUp();

    return YAPP_RET_SUCCESS;
}


/*
 * Calculate start offset for a band
 */
int CalcOffset(float fFMax, float fFMin, double dTSamp, double dDM)
{
    double dDelay = 0.0;
    int iOffset = 0;

    dDelay = (double) -4.148741601e6
             * (((double) 1.0 / pow(fFMax, 2.0))
                - ((double) 1.0 / pow(fFMin, 2.0)))
             * dDM;    /* in ms */
    iOffset = (int) (dDelay / dTSamp);

    return iOffset;
}


/*
 * Prints usage information
 */
void PrintUsage(const char *pcProgName)
{
    (void) printf("Usage: %s [options] <data-file-maxfreq> ... "
                  "<data-file-minfreq>\n",
                  pcProgName);
    (void) printf("    -h  --help                          ");
    (void) printf("Display this usage information\n");
    (void) printf("    -n  --nsamp <samples>               ");
    (void) printf("Number of samples read in one block\n");
    (void) printf("                                        ");
    (void) printf("(default is 4096 samples)\n");
    (void) printf("    -g  --graphics                      ");
    (void) printf("Turn on plotting\n");
    (void) printf("    -i  --invert                        ");
    (void) printf("Invert background and foreground\n");
    (void) printf("                                        ");
    (void) printf("colours in plots\n");
    (void) printf("    -e  --non-interactive               ");
    (void) printf("Run in non-interactive mode\n");
    (void) printf("    -v  --version                       ");
    (void) printf("Display the version\n");

    return;
}

